### PR TITLE
[hotfix] Add xtable prefix to hudi-support jar in demo jupyter node

### PR DESCRIPTION
**Pull request by daragu**
## *Important Read*
- hotfix.

## What is the purpose of the pull request

Add xtable prefix to hudi-support jar in demo jupyter node.

## Brief change log

Add xtable prefix to hudi-support jar in demo jupyter node.

## Verify this pull request

Manually verified the change by running a job locally.

### CODE REVIEW

**Comment by the-other-tim-brown** [comment]
@daragu can you update this script as well: https://github.com/apache/incubator-xtable/blob/main/demo/start_demo.sh#L24

**Comment by daragu** [comment]
hi @the-other-tim-brown, take a review when free, thanks.

**Review by the-other-tim-brown — APPROVED** [review]
Thanks, any other places need update?

**Comment by daragu** [comment]
> Thanks, any other places need update?

hi @the-other-tim-brown, I have checked the entire project and it seems that this place should be the only one left.

**Pull request merged**
