### PR TITLE
Remove azure ci

### PR DESCRIPTION
**Pull request by daragu**
## *Important Read*

Remove azure ci.

## What is the purpose of the pull request

*(For example: This pull request implements the sync for delta format.)*

## Brief change log

The azure ci is pending.
图片

## Verify this pull request

*(Please pick either of the following options)*

This pull request is a trivial rework / code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

*(example:)*

- *Added integration tests for end-to-end.*
- *Added HudiSchemaEvolutionTest to verify the change.*
- *Manually verified the change by running a job locally.*

### CODE REVIEW

**Review by the-other-tim-brown — APPROVED** [review]

**Comment by daragu** [comment]
thanks @the-other-tim-brown

**Comment by jcamachor** [comment]
Thanks, @daragu ! We should probably replace the banner in the README.md now that we are not relying on Azure Pipelines anymore. I'll take care of deleting all the shadow infra Azure/GH infra that needed to be created to support Azure Pipelines in the first place.

**Comment by daragu** [comment]
> badge

👍

**Comment by daragu** [comment]
> Thanks, @daragu ! We should probably replace the badge in the README.md now that we are not relying on Azure Pipelines anymore; I have created #479 for that (also deleting an additional workflow file that was left behind). I'll also take care of deleting all the shadow infra Azure/GH infra that needed to be created to support Azure Pipelines in the first place.

👍

**Pull request merged**
