### PR TITLE
Make build depend on Apache Maven Parent POM

### PR DESCRIPTION
**Pull request by iemejia**
## *Important Read*
- *Please ensure the GitHub issue is mentioned at the beginning of the PR*

## What is the purpose of the pull request

This will simplify maven plugin maintenance so we don't need to update plugins independently to be up to date.
Maven plugin dependencies will be updated by upgrading the parent POM version.

This also removes warnings for non pinned plugin versions and updates some of them.

## Brief change log

- *Added parent pom to root project*
- *Remove explicit plugin versions*

## Verify this pull request

This pull request is already covered by existing tests.

### CODE REVIEW

**Review by wuchunfu — APPROVED** [review]
LGTM

**Comment by iemejia** [comment]
I had to rebase because there was un update that produced a conflict, otherwise the code is the same.

**Comment by jcamachor** [comment]
@xtable-bot run azure

**Comment by iemejia** [comment]
@xtable-bot run azure

**Review by jcamachor — APPROVED** [review]

**Pull request merged**
