### PR TITLE
Move github actions under .github folder

### PR DESCRIPTION
**Pull request by jcamachor**
## What is the purpose of the pull request

This is an addendum to #368. #368 created some action description file for status check on the Azure CI. Those files should be under .github.

### CODE REVIEW

**Comment by jcamachor** [comment]
@ashvina , could you take a look since you reviewed #368? Thanks

**Comment by ashvina** [comment]
Thank you @jcamachor 
I have a small confusion. GitHub searches the .github/workflows directory in your repository for workflow files. Does that mean that the workflow files which are getting moved to .github folder in this repo would also be executed in addition to xtable-ci?

**Comment by jcamachor** [comment]
@ashvina , yes, that's right. In fact, these files correspond to GitHub actions that control the status check in GitHub, while the CI itself is controlled by Azure Pipelines workflow files.

**Review by ashvina — APPROVED** [review]
LGTM 👍

**Pull request merged**
