### PR TITLE
Add new community blogs

### PR DESCRIPTION
**Pull request by dipankarmazumdar**
## What is the purpose of the pull request

- Add new community blogs
- trivial change

### CODE REVIEW

**Comment by the-other-tim-brown** [comment]
@dipankarmazumdar can you split out the demo updates into a separate PR?

**Comment by dipankarmazumdar** [comment]
> @dipankarmazumdar can you split out the demo updates into a separate PR?

@the-other-tim-brown - I separated the 4 blogs. PTAL.

**Comment by the-other-tim-brown** [comment]
> > @dipankarmazumdar can you split out the demo updates into a separate PR?
> 
> @the-other-tim-brown - I separated the 4 blogs. PTAL.

@dipankarmazumdar are you using a different branch I should look at? If not, can you just write up why you need all these files for the blogs? Typically blog updates are just references to other sites and some static content.

**Comment by dipankarmazumdar** [comment]
Created a new separate PR (https://github.com/apache/incubator-xtable/pull/513) to avoid any confusion.

**Pull request closed without merging**
